name: Build and Test Images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: Build image(s)
      run: make build-all
      
    - name: Test image(s)
      run: make test-all
